### ISSUE TITLE
Question about Hi-C filtering

### ISSUE THREAD

**Issue by ericmalekos** [haowenz/chromap#115]
Thank you for building this great tool. I have been generating pair files for Hi-C data and have noticed that a large proportion of reads map uniquely, but less than half of these pass the filtering step.  I am a bit concerned about these lost reads, but this is my first time working with Hi-C data, is this expected?

```
Mapped all reads in 1529.43s.
Number of reads: 348235450.
Number of mapped reads: 320380820.
Number of uniquely mapped reads: 284984054.
Number of reads have multi-mappings: 35396766.
Number of candidates: 14641551676.
Number of mappings: 320380820.
Number of uni-mappings: 284984054.
Number of multi-mappings: 35396766.
Number of output mappings (passed filters): 135907674
Total time: 1875.01s.
```

I am using the following command, which is the Hi-C presets without the low-memory option.

```
chromap -e 4 -q 1 --split-alignment --pairs \
  -r hg38.fa -x hg38.primary_assembly.index \
  -1 "$FASTQ"_1.fastq.gz -2 "$FASTQ"_2.fastq.gz \
  -t 20 -o $FASTQ.pairs
```

**Comment by mourisl** [comment]
The MAPQ computation for HiC is slightly different. Even though a read pair can be uniquely aligned, the secondary alignment could still be only a little bit different. This is exacerbated in Hi-C alignment due to the trimming introduced by the ligation site. Therefore, Chromap has more stringent MAPQ calculation and has a higher fraction of MAPQ 0 mappings among the unique mapped reads.
